src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Models/EmployeeResponse.cs
using System;
using System.Text.Json.Serialization;

namespace Otus.Teaching.Pcf.Administration.MVC.Models
{
    public class EmployeeResponse
    {
        [JsonPropertyName("id")] public Guid Id { get; set; }

        [JsonPropertyName("fullName")] public string FullName { get; set; }
        [JsonPropertyName("email")] public string Email { get; set; }
        [JsonPropertyName("role")] public RoleResponse Role { get; set; }

        [JsonPropertyName("appliedPromocodesCount")]
        public int AppliedPromocodesCount { get; set; }
    }
}

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Models/EmployeeShortResponse.cs
using System;
using System.Text.Json.Serialization;

namespace Otus.Teaching.Pcf.Administration.MVC.Models
{
    public class EmployeeShortResponse
    {
        [JsonPropertyName("id")] public Guid Id { get; set; }
        [JsonPropertyName("fullName")] public string FullName { get; set; }
        [JsonPropertyName("email")] public string Email { get; set; }
    }
}

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Models/EmployeeShortVM.cs
using System;
using System.ComponentModel;

namespace Otus.Teaching.Pcf.Administration.MVC.Models
{
    public class EmployeeShortVM
    {
        [DisplayName("Имя и фамилия")] public string FullName { get; set; }
        [DisplayName("Ид")] public Guid Id { get; set; }
        [DisplayName("Электронный адрес")] public string Email { get; set; }

        public EmployeeShortVM(EmployeeShortResponse response)
        {
            FullName = response.FullName;
            Id = response.Id;
            Email = response.Email;
        }
    }
}

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Models/EmployeeVM.cs
using System;
using System.ComponentModel;

namespace Otus.Teaching.Pcf.Administration.MVC.Models
{
    public class EmployeeVM
    {
        [DisplayName("Имя и фамилия")] public string FullName { get; set; }
        [DisplayName("Ид")] public Guid Id { get; set; }
        [DisplayName("Электронный адрес")] public string Email { get; set; }

        public RoleVM Role { get; set; }

        [DisplayName("Количество примененных промокодов")]
        public int AppliedPromocodesCount { get; set; }

        public EmployeeVM()
        {
        }

        public EmployeeVM(EmployeeResponse employeeResponse)
        {
            FullName = employeeResponse.FullName;
            Email = employeeResponse.Email;
            Id = employeeResponse.Id;
            AppliedPromocodesCount = employeeResponse.AppliedPromocodesCount;
            Role = new RoleVM(employeeResponse.Role);
        }
    }
}

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Models/ErrorViewModel.cs
using System;

namespace Otus.Teaching.Pcf.Administration.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Models/RoleResponse.cs
using System;
using System.Text.Json.Serialization;

namespace Otus.Teaching.Pcf.Administration.MVC.Models
{
    public class RoleResponse
    {
        [JsonPropertyName("id")] public Guid Id { get; set; }
        [JsonPropertyName("name")] public string Name { get; set; }
        [JsonPropertyName("description")] public string Description { get; set; }
    }
}

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Models/RoleVM.cs
using System;
using System.ComponentModel;

namespace Otus.Teaching.Pcf.Administration.MVC.Models
{
    public class RoleVM
    {
        public RoleVM()
        {
        }

        public RoleVM(RoleResponse employeeResponseRole)
        {
            Description = employeeResponseRole.Description;
            Id = employeeResponseRole.Id;
            Name = employeeResponseRole.Name;
        }

        [DisplayName("Ид")] public Guid Id { get; set; }
        [DisplayName("Описание")] public string Description { get; set; }
        [DisplayName("Название")] public string Name { get; set; }
    }
}

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Otus.Teaching.Pcf.Administration.Core.Domain.Administration;
using Otus.Teaching.Pcf.Administration.MVC.Models;

namespace Otus.Teaching.Pcf.Administration.MVC.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ILogger<EmployeesController> _logger;
        private readonly HttpClient _apiClient;

        public EmployeesController(ILogger<EmployeesController> logger, HttpClient apiClient)
        {
            _logger = logger;
            _apiClient = apiClient;
        }

        public async Task<IActionResult> Index()
        {
            var res = await _apiClient.GetAsync("http://localhost:8091/api/v1/Employees");
            if (!res.IsSuccessStatusCode) return BadRequest();
            var body = await res.Content.ReadAsStringAsync();
            var list = JsonSerializer.Deserialize<IEnumerable<EmployeeShortResponse>>(body);
            var vmRes = list.Select(s => new EmployeeShortVM(s));
            return View(vmRes);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }

        public async Task<ActionResult> Details(Guid id)
        {
            var res = await _apiClient.GetAsync("http://localhost:8091/api/v1/Employees/" + id);
            if (!res.IsSuccessStatusCode) return BadRequest();
            var body = await res.Content.ReadAsStringAsync();
            var respone = JsonSerializer.Deserialize<EmployeeResponse>(body);
            var vmRes = new EmployeeVM(respone);
            return View(vmRes);
        }

        public async Task<IActionResult> UpdateAppliedPromocodesCount(EmployeeVM employeeVm)
        {
            var res = await _apiClient.PostAsync(
                $"http://localhost:8091/api/v1/Employees/{employeeVm.Id.ToString()}/appliedPromocodes", null);
            if (!res.IsSuccessStatusCode) return BadRequest();
            return Redirect("/Employees/Details/" + employeeVm.Id);
        }
    }
}

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Otus.Teaching.Pcf.Administration.MVC.Models;

namespace Otus.Teaching.Pcf.Administration.MVC.Controllers
{
    public class RolesController : Controller
    {
        private readonly ILogger<EmployeesController> _logger;
        private readonly HttpClient _apiClient;

        public RolesController(ILogger<EmployeesController> logger, HttpClient apiClient)
        {
            _logger = logger;
            _apiClient = apiClient;
        }

        // GET
        public async Task<IActionResult> Index()
        {
            var res = await _apiClient.GetAsync("http://localhost:8091/api/v1/Roles");
            if (!res.IsSuccessStatusCode) return BadRequest();
            var body = await res.Content.ReadAsStringAsync();
            var list = JsonSerializer.Deserialize<IEnumerable<RoleResponse>>(body);
            var vmRes = list.Select(s => new RoleVM(s));
            return View(vmRes);
        }
    }
}

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Views/Employees/Details.cshtml
@model EmployeeVM

@{
    ViewBag.Title = "Пользователь";
    Layout = "_Layout";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateAppliedPromocodesCount">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <h2>Пользователь</h2>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control"/>
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppliedPromocodesCount" class="control-label"></label>
                <input asp-for="AppliedPromocodesCount" class="form-control"/>
                <span asp-validation-for="AppliedPromocodesCount" class="text-danger"></span>
            </div>
            <h2>Роль пользователя</h2>
            <div class="form-group">
                <label asp-for="Role.Id" class="control-label"></label>
                <input asp-for="Role.Id" class="form-control"/>
                <span asp-validation-for="Role.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role.Description" class="control-label"></label>
                <input asp-for="Role.Description" class="form-control"/>
                <span asp-validation-for="Role.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role.Name" class="control-label"></label>
                <input asp-for="Role.Name" class="form-control"/>
                <span asp-validation-for="Role.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="UpdateAppliedPromocodesCount" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Views/Employees/Index.cshtml
@model IEnumerable<Otus.Teaching.Pcf.Administration.MVC.Models.EmployeeShortVM>

@{
    ViewBag.Title = "Пользователи";
    Layout = "_Layout";
}
<h2>Пользователи</h2>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Детали</a>
            </td>
        </tr>
    }
    </tbody>
</table>

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Views/Roles/Index.cshtml
@model IEnumerable<Otus.Teaching.Pcf.Administration.MVC.Models.RoleVM>

@{
    ViewBag.Title = "Пользователи";
    Layout = "_Layout";
}
<h2>Пользователи</h2>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
    }
    </tbody>
</table>

src/Otus.Teaching.Pcf.Administration/Otus.Teaching.Pcf.Administration.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Otus.Teaching.Pcf.Administration.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Index">Otus.Teaching.Pcf.Administration.MVC</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Сотрудники</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Роли</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - Otus.Teaching.Pcf.Administration.MVC
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>